complexity:
  active: false

naming:
  active: false
  
comments:
  AbsentOrWrongFileLicense:
    active: false
    licenseTemplateFile: 'license.template'
    licenseTemplateIsRegex: false
  DeprecatedBlockTag:
    active: true
  EndOfSentenceFormat:
    active: true
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: true

build:
  maxIssues: 10
  weights:
    comments: 4
    DeprecatedBlockTag: 2
    EndOfSentenceFormat: 1

console-reports:
  active: true
  exclude:
    #  - 'ProjectStatisticsReport'
    #  - 'ComplexityReport'
    #  - 'NotificationReport'
    #  - 'FindingsReport'
    - 'FileBasedFindingsReport'
    #  - 'LiteFindingsReport'


processors:
    active: true
    exclude:
      # - 'DetektProgressListener'
      - 'KtFileCountProcessor'
      - 'PackageCountProcessor'
      - 'ClassCountProcessor'
      - 'FunctionCountProcessor'
      - 'PropertyCountProcessor'
      # - 'ProjectComplexityProcessor'
      # - 'ProjectCognitiveComplexityProcessor'
      - 'ProjectLLOCProcessor'
      - 'ProjectCLOCProcessor'
      - 'ProjectLOCProcessor'
      - 'ProjectSLOCProcessor'
      - 'LicenseHeaderLoaderExtension'
