name: Check and Publish

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    name: Run build, tests and detekt
    uses: TimerErTim/Knevo/.github/workflows/check.yml@master

  publish:
    # The type of runner that the job will run on
    name: Publish
    runs-on: ubuntu-latest
    needs: check

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Publish
        run: ./gradlew -PMAVEN_UPLOAD_USER="${{ secrets.SONATYPE_USERNAME }}" -PMAVEN_UPLOAD_PWD="${{ secrets.SONATYPE_PASSWORD }}" -PGPG_SIGNING_KEY="${{ secrets.GPG_SIGNING_KEY }}" -PGPG_SIGNING_PASSWORD="${{ secrets.GPG_SIGNING_PASSWORD }}" publish
